### ISSUE TITLE
support introspection of JEXL expressions

### ISSUE THREAD

**Issue by gregglind** [TomFrost/Jexl#31] opened 2017-07-05 14:32 UTC
Use case:
- turn a JEXL back into a form that can be reasoned about / described.

Possible path:
- expose a 'parse' method on `jexl` instances.

**Comment by TomFrost** [comment] 2019-01-08 04:39
Closing as dupe of #29 -- let me know if I've misunderstood! (And sorry for the ultra-late reply)

**Closed by TomFrost** 2019-01-08 04:39 UTC
